CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(64) NOT NULL UNIQUE,
    dept_name VARCHAR(64) NOT NULL,
    dept_type VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE regist_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regist_code VARCHAR(64) NOT NULL UNIQUE,
    regist_name VARCHAR(64) NOT NULL,
    regist_fee DECIMAL(10, 2) NOT NULL,
    regist_quota INT NOT NULL,
    sequence_no INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE settle_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settle_code VARCHAR(64) NOT NULL UNIQUE,
    settle_name VARCHAR(64) NOT NULL,
    sequence_no INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_name VARCHAR(64) NOT NULL,
    department_id BIGINT NOT NULL,
    regist_level_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE `register` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL UNIQUE,
    case_number VARCHAR(64) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    gender VARCHAR(16) NOT NULL,
    card_number VARCHAR(32),
    birthday DATE,
    age INT,
    age_type VARCHAR(16),
    home_address VARCHAR(255),
    visit_date TIMESTAMP NOT NULL,
    noon VARCHAR(16) NOT NULL,
    department_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    regist_level_id BIGINT NOT NULL,
    settle_category_id BIGINT NOT NULL,
    is_book BOOLEAN NOT NULL DEFAULT FALSE,
    regist_method VARCHAR(32) NOT NULL,
    visit_state VARCHAR(32) NOT NULL,
    regist_money DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE charge_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    state VARCHAR(32) NOT NULL,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (item_type, source_id)
);

CREATE TABLE disease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_code VARCHAR(50) NOT NULL UNIQUE,
    disease_name VARCHAR(255) NOT NULL,
    disease_icd VARCHAR(50),
    disease_category VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE medical_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL UNIQUE,
    chief_complaint VARCHAR(500),
    present_illness VARCHAR(10000),
    present_treatment VARCHAR(10000),
    past_history VARCHAR(10000),
    allergy_history VARCHAR(10000),
    physical_examination VARCHAR(10000),
    examination_proposal VARCHAR(10000),
    precaution VARCHAR(10000),
    diagnosis VARCHAR(10000),
    treatment_plan VARCHAR(10000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medical_record_disease (
    medical_record_id BIGINT NOT NULL,
    disease_id BIGINT NOT NULL,
    diagnosis_type VARCHAR(32) NOT NULL,
    PRIMARY KEY (medical_record_id, disease_id)
);

CREATE TABLE drug_stock (
    drug_id BIGINT PRIMARY KEY,
    quantity INT NOT NULL,
    version BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
