CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(64) NOT NULL UNIQUE,
    dept_name VARCHAR(64) NOT NULL,
    dept_type VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE drug_stock (
    drug_id BIGINT PRIMARY KEY,
    quantity INT NOT NULL,
    version BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prescription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL,
    drug_id BIGINT NOT NULL,
    drug_usage VARCHAR(500) NOT NULL,
    drug_number INT NOT NULL,
    state VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispensed_at TIMESTAMP,
    dispensed_by BIGINT
);

CREATE TABLE drug_stock_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id BIGINT NOT NULL,
    prescription_id BIGINT,
    transaction_type VARCHAR(32) NOT NULL,
    quantity INT NOT NULL,
    quantity_before INT NOT NULL,
    quantity_after INT NOT NULL,
    operator_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE check_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL,
    medical_technology_id BIGINT NOT NULL,
    request_info VARCHAR(1000),
    body_position VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executor_employee_id BIGINT,
    result_employee_id BIGINT,
    executed_at TIMESTAMP,
    result CLOB,
    state VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    remark VARCHAR(1000)
);

CREATE TABLE inspection_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL,
    medical_technology_id BIGINT NOT NULL,
    request_info VARCHAR(1000),
    body_position VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executor_employee_id BIGINT,
    result_employee_id BIGINT,
    executed_at TIMESTAMP,
    result CLOB,
    state VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    remark VARCHAR(1000)
);

CREATE TABLE disposal_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT NOT NULL,
    medical_technology_id BIGINT NOT NULL,
    request_info VARCHAR(1000),
    body_position VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executor_employee_id BIGINT,
    result_employee_id BIGINT,
    executed_at TIMESTAMP,
    result CLOB,
    state VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    remark VARCHAR(1000)
);
