CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(64) NOT NULL UNIQUE,
    dept_name VARCHAR(64) NOT NULL,
    dept_type VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE regist_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regist_code VARCHAR(64) NOT NULL UNIQUE,
    regist_name VARCHAR(64) NOT NULL,
    regist_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    regist_quota INT NOT NULL DEFAULT 0,
    sequence_no INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE settle_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settle_code VARCHAR(64) NOT NULL UNIQUE,
    settle_name VARCHAR(64) NOT NULL,
    sequence_no INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE scheduling (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(64) NOT NULL,
    week_rule CHAR(14) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE disease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_code VARCHAR(50) NOT NULL UNIQUE,
    disease_name VARCHAR(255) NOT NULL,
    disease_icd VARCHAR(50),
    disease_category VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE drug_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_code VARCHAR(64) NOT NULL UNIQUE,
    drug_name VARCHAR(255) NOT NULL,
    drug_format VARCHAR(255) NOT NULL,
    drug_unit VARCHAR(16) NOT NULL,
    manufacturer VARCHAR(255),
    drug_dosage VARCHAR(64),
    drug_type VARCHAR(64),
    drug_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    mnemonic_code VARCHAR(64),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE medical_technology (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tech_code VARCHAR(64) NOT NULL UNIQUE,
    tech_name VARCHAR(128) NOT NULL,
    tech_format VARCHAR(64),
    tech_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tech_type VARCHAR(32) NOT NULL,
    price_type VARCHAR(64),
    department_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_name VARCHAR(64) NOT NULL,
    department_id BIGINT NOT NULL,
    regist_level_id BIGINT,
    scheduling_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    employee_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    module_code VARCHAR(64) NOT NULL
);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    module_code VARCHAR(64) NOT NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(64),
    target_id VARCHAR(64),
    detail VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE drug_stock (
    drug_id BIGINT PRIMARY KEY,
    quantity INT NOT NULL,
    version BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
